---
name: Audio-Ofa
version: 0.02_02
author:
  - 'Christoph Bussenius <pepe@cpan.org>'
abstract: Bindings for libofa
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
configure_requires:
  ExtUtils::PkgConfig: 0
build_requires:
  Compress::Zlib: 0
  ExtUtils::PkgConfig: 0
  Module::Build: 0
  Test::More: 0
provides:
  Audio::Ofa:
    file: lib/Audio/Ofa.pm
    version: 0.02_02
no_index:
  directory: example
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
